# Generated by Django 5.2.4 on 2025-09-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flightticket_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
