# Generated by Django 5.2.4 on 2025-09-24 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usersession_user_usersession_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSession',
            new_name='UserChatSession',
        ),
    ]
